#!/bin/bash



COM=0

while [ true ]

do

LIST1="1. Nazwa pliku: $NAME"

LIST2="2. Katalog: $DIR"

LIST3="3. Rozmiar pliku(wiekszy niz podana wartosc w MB): $BIGGER"

LIST4="4. Rozmiar pliku(mniejszy niz podana wartosc w MB): $SMALL"

LIST5="5. Kiedy ostatnio dokonano modyfikacji(w godzinach): $DATE"

LIST6="6. Zawartosc pliku: $SEARCHING"

LIST7="7. Szukaj"

LIST8="8. Koniec"



MENU=("$LIST1" "$LIST2" "$LIST3" "$LIST4" "$LIST5" "$LIST6" "$LIST7" "$LIST8")

COM=$(zenity --list --column=MENU "${MENU[@]}" --height 400 --width 300)



case $COM in

	$LIST1)NAME=$(zenity --entry --title "Nazwa" --text "Wprowadz nazwe pliku: ");;

	$LIST2)DIR=$(zenity --entry --title "Katalog" --text "Wprowadz nazwe katalogu: ");;

	$LIST3)BIGGER=$(zenity --entry --title "Wielkosc pliku > wartosc " --text "Program będzie wyszukiwał pliki większe niż podana wartość(MB)")

	if [[ -n BIGGER ]]; then PR_BIGGER="-size +${BIGGER}M"; fi;;

	$LIST4)SMALL=$(zenity --entry --title "Wielkosc pliku < wartosc " --text "Program będzie wyszukiwał pliki mniejsze niż podana wartość(MB)")

	if [[ -n SMALL ]]; then PR_SMALL="-size -${SMALL}M"; fi

	;;

	$LIST5)DATE=$(zenity --entry --title "Czas modyfikacji" --text "Podaj do ilu godzin temu plik był modydikowany: ")

	if [[ -n DATE ]]; then PR_DATE="-mtime -$DATE"; fi

	;;

	$LIST6)SEARCHING=$(zenity --entry --title "Zawiera" --text "Podaj ciąg znaków który ma być zawarty w pliku: ")

	if [[ -n DATA ]]; then PR_SEARCH=" -exec grep -l -i $SEARCHING {} +"; fi

	;;

	$LIST7)if [[ -z DIR ]]; then

	RESULT=$(find -type f -name "$NAME" $PR_BIGGER $PR_SMALL $PR_DATE $PR_SEARCH)

	zenity --info --title "Wynik poszukiwan" --text "$RESULT" --height 200 --width 200

	else

	RESULT=$(find $DIR -type f -name "$NAME" $PR_BIGGER $PR_SMALL $PR_DATE $PR_SEARCH)

	zenity --info --title "Wynik poszukiwan" --text "$RESULT" --height 200 --width 200

	fi

	;;

	$LIST8)exit;;

esac

done
