#!/bin/bash



COM=0

while [ true ]

do

echo "1. Nazwa pliku: $NAME"

echo "2. Katalog: $DIR"

echo "3. Rozmiar pliku(wiekszy niz podana wartosc w MB): $BIGGER"

echo "4. Rozmiar pliku(mniejszy niz podana wartosc w MB): $SMALL"

echo "5. Kiedy ostatnio dokonano modyfikacji(w godzinach): $DATE"

echo "6. Zawartosc pliku: $SEARCHING"

echo "7. Szukaj"

echo "8. Koniec"



read COM

clear

case $COM in

	1)read NAME;;

	2)read DIR;;

	3)read BIGGER

	if [[ -n BIGGER ]]; then PR_BIGGER="-size +${BIGGER}M"; fi;;

	4)read SMALL

	if [[ -n SMALL ]]; then PR_SMALL="-size -${SMALL}M"; fi

	;;

	5)read DATE

	if [[ -n DATE ]]; then PR_DATE="-mtime -$DATE"; fi

	;;

	6)read SEARCHING

	if [[ -n DATA ]]; then PR_SEARCH=" -exec grep -l -i $SEARCHING {} +"; fi

	;;

	7)if [[ -z DIR ]]; then

	find -type f -name "$NAME" $PR_BIGGER $PR_SMALL $PR_DATE 	$PR_SEARCH

	else

	find $DIR -type f -name "$NAME" $PR_BIGGER $PR_SMALL $PR_DATE $PR_SEARCH

	fi

	;;

	8)exit;;

esac

done
