#!/bin/bash

grep "OK DOWNLOAD" cdlinux.ftp.log | cut -d '"' -f 2,4 | sort -u| cut -d '"' -f  2| grep "\.iso" | sed 's#.*/##' | sort > temp.txt 

grep " 200 " cdlinux.www.log | cut -d " " -f 1,7 | sort -u | rev | cut  -d "/" -f 1 | rev | grep "\.iso" | cut -d " " -f 1| cut -d "?" -f 1 | grep "cdlinux-*" | sed "s/.*%2F//" | sort >> temp.txt

cat temp.txt | sort | uniq -c | sort -nr
